# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ratespiel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from ratespiel import main
import time
from datetime import datetime
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ratespiel(object):
    def setupUi(self, Ratespiel):
        Ratespiel.setObjectName("Ratespiel")
        Ratespiel.resize(578, 464)
        self.centralwidget = QtWidgets.QWidget(Ratespiel)
        self.centralwidget.setObjectName("centralwidget")

        self.lineEdit_ober_grenze = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ober_grenze.setGeometry(QtCore.QRect(350, 20, 181, 22))
        self.lineEdit_ober_grenze.setObjectName("lineEdit")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 281, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Cond")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Cond")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)

        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")

        self.lineEdit_unter_grenze = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_unter_grenze.setGeometry(QtCore.QRect(350, 50, 181, 22))
        self.lineEdit_unter_grenze.setObjectName("lineEdit_2")

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 160, 401, 192))
        self.textBrowser.setObjectName("textBrowser")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 111, 16))
        self.label_3.setObjectName("label_3")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 80, 93, 28))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clicked)

        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(150, 120, 271, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setValue(0)

        Ratespiel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ratespiel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 26))
        self.menubar.setObjectName("menubar")
        self.menu_abl = QtWidgets.QMenu(self.menubar)
        self.menu_abl.setObjectName("menu_abl")
        Ratespiel.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(Ratespiel)
        self.statusbar.setObjectName("statusbar")
        Ratespiel.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_abl.menuAction())

        self.retranslateUi(Ratespiel)
        QtCore.QMetaObject.connectSlotsByName(Ratespiel)

    def retranslateUi(self, Ratespiel):
        _translate = QtCore.QCoreApplication.translate
        Ratespiel.setWindowTitle(_translate("Ratespiel", "Ratespiel"))
        self.label.setText(_translate("Ratespiel", "Geben Sie bitte die obere Grenze ein:"))
        self.label_2.setText(_translate("Ratespiel", "Geben Sie bitte die untere Grenze ein:"))
        self.label_3.setText(_translate("Ratespiel", "Resutate: "))
        self.pushButton.setText(_translate("Ratespiel", "Angehen!!!"))
        self.menu_abl.setTitle(_translate("Ratespiel", "das ist Programm, das du unbedingt baruchst"))

    def clicked(self):
        start = datetime.now()
        try:
            res, treffer = main(int(self.lineEdit_ober_grenze.text()), int(self.lineEdit_unter_grenze.text()))
        except Exception as ex:
            self.textBrowser.setText("Error {}".format(ex))
            return None
        self.progressBar.setMaximum(res)
        for i in range(1, res + 1):
            time.sleep(0.05)
            self.progressBar.setValue(i)
        end = datetime.now()
        string_for_output = "Treffer!!!\nDie Anzahl von Versuche ist {}\nGebrauchte Zeit ist {}\nStart {}\nend {}\nResultat {}".format(
            res, (end - start), start, end, treffer)
        self.textBrowser.setText(string_for_output)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ratespiel = QtWidgets.QMainWindow()
    ui = Ui_Ratespiel()
    ui.setupUi(Ratespiel)
    Ratespiel.show()
    sys.exit(app.exec_())
